added information about mock calls CallThrough
sapegin/jest-cheat-sheet pull request #4
Opened 2018-05-11 13:12 UTC by gsabatie

2018-05-11 14:45 UTC, lirantal commented on Readme.md
> +const spyWithCallToRealFunction = jest.spyOn(ajax, 'request').andCallThrough()
Maybe add a comment that this is also the default behavior without adding `andCallThrough()` ?

2018-05-11 15:36 UTC, sapegin requested changes
Thanks! A few notes.

2018-05-11 15:36 UTC, sapegin commented on Readme.md
> +### Mock object methods and call through to the real function
I'd add an explanation what “call through” means.

2018-05-11 15:36 UTC, sapegin commented on Readme.md
> +### Verify mock calling
I think we have enough examples in the “Matchers” section. It probably could be improved, but adding a new sections that is almost the same isn't a good solution.

2018-05-15 12:23 UTC, gsabatie commented on Readme.md
> +### Verify mock calling
yes sur

2018-05-25 08:50 UTC, closed without merging